version: '3'

services:
  # MySQL
  db:
    image: mysql:8.0
    container_name: local
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./local/data:/var/lib/mysql
      - ./local/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./local/sql:/docker-entrypoint-initdb.d
    ports:
      - "127.0.0.1:3306:3306"
