name: Migration

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  migrate-db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Setup Env
        run: |
          echo "CLOUDSQL_INSTANCE_CONNECTION_NAME=${{ secrets.CLOUDSQL_CONNECTION_NAME }}" > .env
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
          echo "MYSQL_PASSWORD='${{ secrets.MYSQL_PASSWORD }}'" >> .env
          echo '${{ secrets.GCP_SA_KEY }}' > ./config/sa_key.json

      - name: Start Cloud SQL Proxy
        run: |
          docker-compose up -d

      - name: Install migrate
        run: |
          curl -L https://packagecloud.io/golang-migrate/migrate/gpgkey | apt-key add -
          echo "deb https://packagecloud.io/golang-migrate/migrate/ubuntu/dists/focal/Release $(lsb_release -sc) main" > /etc/apt/sources.list.d/migrate.list
          apt-get update
          apt-get install -y migrate

      - name: Migrate DB (up)
        run: ./scripts/migrations.sh
