name: Check mgrations

on: pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Setup Env
        run: |
          echo "MYSQL_USER=root" > .env
          echo "MYSQL_PASSWORD=password" >> .env
      
      - name: Run local MySQL Server
        run: ./scripts/start_local.sh up -d
      
      - name: Install migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-arm64.tar.gz | tar xvz
      
      - name: migration
        run: ./scripts/migrations.sh
