name: Migration

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  migrate-db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: supplypike/setup-bin@v1
        with:
          uri: 'https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz'
          name: 'migrate'
          version: 'v4.15.2'
      
      - name: Setup Env
        run: |
          echo "CLOUDSQL_INSTANCE_CONNECTION_NAME=${{ secrets.CLOUDSQL_CONNECTION_NAME }}" > .env
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
          echo "MYSQL_PASSWORD='${{ secrets.MYSQL_PASSWORD }}'" >> .env
          echo '${{ secrets.GCP_SA_KEY }}' > ./config/sa_key.json

      - name: Start Cloud SQL Proxy
        run: |
          docker-compose up -d

      - name: Sleep for 10 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '10s'

      - name: Migrate DB (up)
        run: ./scripts/migrations.sh
