name: Check mgrations

on: pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Setup Env
        run: |
          echo "MYSQL_USER=root" > .env
          echo "MYSQL_PASSWORD=password" >> .env
      
      - name: Run local MySQL Server
        run: ./scripts/start_local.sh up -d
      
      - name: Install migrate
        run: |
          curl -L https://packagecloud.io/golang-migrate/migrate/gpgkey | apt-key add -
          echo "deb https://packagecloud.io/golang-migrate/migrate/ubuntu/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/migrate.list
          apt-get update
          apt-get install -y migrate
      
      - name: migration
        run: ./scripts/migrations.sh
